<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventBooking.TicketMgt.Domain\EventBooking.TicketMgt.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Categories\Commands\" />
    <Folder Include="Features\Events\Commands\CreateEvent\" />
    <Folder Include="Features\Orders\Commands\" />
    <Folder Include="Features\Orders\Queries\" />
  </ItemGroup>

</Project>
